name: Bleeding edge release builds

on:
    push:
        branches:
            - main

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0



            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 6.0.x

            - name: Restore Dependencies
              run: dotnet restore
              working-directory: ./MistWX-i2Me

            - name: Build Linux Executable
              run: dotnet build -c Release --no-restore
              working-directory: ./MistWX-i2Me
            

            - uses: "actions/upload-artifact@v4"
              with:
                name: MistWX-i2ME-artifact-linux-x64
                path: ${{github.workspace}}/MistWX-i2Me/bin/Release/net6.0/**
                if-no-files-found: error
            # TODO: Add Testing

    build-windows:
        runs-on: windows-latest

        steps:
            - uses: "actions/checkout@v2"
              with:
                fetch-depth: 0


            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 6.0.x
            
            - name: Restore Dependencies
              run: dotnet restore
              working-directory: ./MistWX-i2Me

            - name: Build Windows Executable
              run: dotnet build -c Release --no-restore
              working-directory: ./MistWX-i2Me

            
            - uses: "actions/upload-artifact@v4"
              with:
                name: MistWX-i2ME-artifact-windows-x64
                path: ${{github.workspace}}/MistWX-i2Me/bin/Release/net6.0/**
                if-no-files-found: error
